In [2]:
import numpy as np, pandas as pd,matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/mnt/mydata/python_projects/python_projects/iris/data/car data.csv")
df = df.drop_duplicates()
df.dropna()

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [4]:
df['Car_Name'].values
Car_name = {}
fromdataset = df['Car_Name'].values 
for i in range(len(fromdataset)):
    if  fromdataset[i] not in Car_name:
        Car_name[fromdataset[i]] =i
Car_name

{'ritz': 0,
 'sx4': 1,
 'ciaz': 2,
 'wagon r': 3,
 'swift': 4,
 'vitara brezza': 5,
 's cross': 7,
 'alto 800': 10,
 'ertiga': 13,
 'dzire': 14,
 'alto k10': 19,
 'ignis': 20,
 '800': 36,
 'baleno': 39,
 'omni': 43,
 'fortuner': 49,
 'innova': 51,
 'corolla altis': 54,
 'etios cross': 55,
 'etios g': 57,
 'etios liva': 64,
 'corolla': 76,
 'etios gd': 80,
 'camry': 84,
 'land cruiser': 85,
 'Royal Enfield Thunder 500': 98,
 'UM Renegade Mojave': 99,
 'KTM RC200': 100,
 'Bajaj Dominar 400': 101,
 'Royal Enfield Classic 350': 102,
 'KTM RC390': 103,
 'Hyosung GT250R': 104,
 'Royal Enfield Thunder 350': 105,
 'KTM 390 Duke ': 110,
 'Mahindra Mojo XT300': 111,
 'Bajaj Pulsar RS200': 118,
 'Royal Enfield Bullet 350': 120,
 'Royal Enfield Classic 500': 122,
 'Bajaj Avenger 220': 124,
 'Bajaj Avenger 150': 125,
 'Honda CB Hornet 160R': 126,
 'Yamaha FZ S V 2.0': 127,
 'Yamaha FZ 16': 129,
 'TVS Apache RTR 160': 132,
 'Bajaj Pulsar 150': 133,
 'Honda CBR 150': 134,
 'Hero Extreme': 135,
 'Bajaj Avenger 220 dtsi': 137,
 'Bajaj Avenger 150 street': 139,
 'Yamaha FZ  v 2.0': 140,
 'Bajaj Pulsar  NS 200': 142,
 'Bajaj Pulsar 220 F': 146,
 'TVS Apache RTR 180': 148,
 'Hero Passion X pro': 149,
 'Bajaj Pulsar NS 200': 150,
 'Yamaha Fazer ': 152,
 'Honda Activa 4G': 153,
 'TVS Sport ': 154,
 'Honda Dream Yuga ': 156,
 'Bajaj Avenger Street 220': 158,
 'Hero Splender iSmart': 162,
 'Activa 3g': 163,
 'Hero Passion Pro': 164,
 'Honda CB Trigger': 166,
 'Yamaha FZ S ': 168,
 'Bajaj Pulsar 135 LS': 170,
 'Activa 4g': 171,
 'Honda CB Unicorn': 172,
 'Hero Honda CBZ extreme': 173,
 'Honda Karizma': 174,
 'Honda Activa 125': 175,
 'TVS Jupyter': 176,
 'Hero Honda Passion Pro': 178,
 'Hero Splender Plus': 179,
 'Honda CB Shine': 180,
 'Bajaj Discover 100': 181,
 'Suzuki Access 125': 183,
 'TVS Wego': 184,
 'Honda CB twister': 185,
 'Hero Glamour': 186,
 'Hero Super Splendor': 187,
 'Bajaj Discover 125': 189,
 'Hero Hunk': 190,
 'Hero  Ignitor Disc': 191,
 'Hero  CBZ Xtreme': 192,
 'Bajaj  ct 100': 193,
 'i20': 199,
 'grand i10': 200,
 'i10': 201,
 'eon': 202,
 'xcent': 204,
 'elantra': 209,
 'creta': 210,
 'verna': 213,
 'city': 249,
 'brio': 250,
 'amaze': 257,
 'jazz': 261}

In [5]:
df['Car_Name'] = df['Car_Name'].map(Car_name)
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,0,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,1,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,2,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,3,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,4,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,249,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,250,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,249,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,249,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,250,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [6]:
Fuel = {'Diesel':0, 'Petrol':1}
df['Fuel_Type'] = df['Fuel_Type'].map(Fuel)
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,0,2014,3.35,5.59,27000,1.0,Dealer,Manual,0
1,1,2013,4.75,9.54,43000,0.0,Dealer,Manual,0
2,2,2017,7.25,9.85,6900,1.0,Dealer,Manual,0
3,3,2011,2.85,4.15,5200,1.0,Dealer,Manual,0
4,4,2014,4.60,6.87,42450,0.0,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,249,2016,9.50,11.60,33988,0.0,Dealer,Manual,0
297,250,2015,4.00,5.90,60000,1.0,Dealer,Manual,0
298,249,2009,3.35,11.00,87934,1.0,Dealer,Manual,0
299,249,2017,11.50,12.50,9000,0.0,Dealer,Manual,0
300,250,2016,5.30,5.90,5464,1.0,Dealer,Manual,0

In [7]:
df['Selling_type'] = np.where(df["Selling_type"] == "Dealer",1,0)
df

,Car_Name,Year,Selling_Price,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,0,2014,3.35,5.59,27000,1.0,1,Manual,0
1,1,2013,4.75,9.54,43000,0.0,1,Manual,0
2,2,2017,7.25,9.85,6900,1.0,1,Manual,0
3,3,2011,2.85,4.15,5200,1.0,1,Manual,0
4,4,2014,4.60,6.87,42450,0.0,1,Manual,0
...,...,...,...,...,...,...,...,...,...
296,249,2016,9.50,11.60,33988,0.0,1,Manual,0
297,250,2015,4.00,5.90,60000,1.0,1,Manual,0
298,249,2009,3.35,11.00,87934,1.0,1,Manual,0
299,249,2017,11.50,12.50,9000,0.0,1,Manual,0
300,250,2016,5.30,5.90,5464,1.0,1,Manual,0

In [8]:
df['Transmission'] = np.where(df['Transmission'] == 'Manual',1,0)

In [9]:
x = {"Car_Name":df['Car_Name'].values,'Year':df['Year'].values,'Present_Price':df['Present_Price'].values,'Driven_kms':df['Driven_kms'].values,'Fuel_Type':df['Fuel_Type'].values,'Selling_type':df['Selling_type'].values,'Transmission':df['Transmission'].values,'Owner':df['Owner'].values}
x = pd.DataFrame(x)
y = {"Selling_Price":df["Selling_Price"]}
y = pd.DataFrame(y)

In [10]:
x

,Car_Name,Year,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
0,0,2014,5.59,27000,1.0,1,1,0
1,1,2013,9.54,43000,0.0,1,1,0
2,2,2017,9.85,6900,1.0,1,1,0
3,3,2011,4.15,5200,1.0,1,1,0
4,4,2014,6.87,42450,0.0,1,1,0
...,...,...,...,...,...,...,...,...
294,249,2016,11.60,33988,0.0,1,1,0
295,250,2015,5.90,60000,1.0,1,1,0
296,249,2009,11.00,87934,1.0,1,1,0
297,249,2017,12.50,9000,0.0,1,1,0
298,250,2016,5.90,5464,1.0,1,1,0

In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state=42)
import xgboost as xg
from sklearn.metrics import r2_score, mean_absolute_error

In [12]:
X_train

,Car_Name,Year,Present_Price,Driven_kms,Fuel_Type,Selling_type,Transmission,Owner
6,2,2015,8.12,18796,1.0,1,1,0
183,183,2008,0.58,1900,1.0,0,0,0
185,185,2013,0.51,32000,1.0,0,1,0
146,146,2010,0.94,45000,1.0,0,1,0
30,0,2011,4.89,54200,1.0,1,1,0
...,...,...,...,...,...,...,...,...
188,133,2008,0.75,60000,1.0,0,1,0
71,54,2013,18.61,56001,1.0,1,1,0
106,105,2016,1.50,18000,1.0,0,1,0
270,249,2015,10.00,27600,1.0,1,1,0
102,102,2017,1.47,4100,1.0,0,1,0

In [13]:
model =xg.XGBRegressor( objective='reg:gamma',
        n_estimators=100,
        learning_rate=0.6,
        max_depth=3,
        tree_method='hist',
        min_child_weight=3,
        random_state=42
         )
model.fit(X_train, Y_train,verbose=True)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.6, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=3,
             max_leaves=None, min_child_weight=3, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [14]:
y_pred = model.predict(X_test)
r2score = r2_score(Y_test,y_pred)
absoluteerror= mean_absolute_error(Y_test,y_pred)
print(f'r2_score:{r2score:.2f}\nabsolute error {absoluteerror:.4f}')

r2_score:0.95
absolute error 0.6835

In [15]:
import joblib
joblib.dump(model,"./models/XGBRegressor.lb")

['./models/XGBRegressor.lb']